In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:

pd.set_option('display.max_columns', None)

In [4]:
!pip install pandas openpyxl

Requirement already satisfied: pandas in /Users/robertoaltran/opt/anaconda3/lib/python3.9/site-packages (1.3.4)
Requirement already satisfied: openpyxl in /Users/robertoaltran/opt/anaconda3/lib/python3.9/site-packages (3.0.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/robertoaltran/opt/anaconda3/lib/python3.9/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /Users/robertoaltran/opt/anaconda3/lib/python3.9/site-packages (from pandas) (2021.3)
Requirement already satisfied: numpy>=1.17.3 in /Users/robertoaltran/opt/anaconda3/lib/python3.9/site-packages (from pandas) (1.20.3)
Requirement already satisfied: et-xmlfile in /Users/robertoaltran/opt/anaconda3/lib/python3.9/site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in /Users/robertoaltran/opt/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)

In [5]:
url = 'https://raw.githubusercontent.com/robertoaltran/Population/main/2018-SA1-dataset-household-AucklandRegion.csv'
data2 = pd.read_csv(url)

In [6]:
data2 = data2.iloc[:, [0, 1, 4]]

In [7]:
headers = data2.iloc[0]
data2 = data2[1:]
data2.columns = headers
data2.head()

0 Area_Code              Area_Description  2018.0
1    110200           Okahukura Peninsula   522.0
2    110300   Inlet Kaipara Harbour South     0.0
3    110400                   Cape Rodney  1275.0
4    110500                     Wellsford   654.0
5    110600  Oceanic Auckland Region East     6.0

**Total households in occupied private dwellings**:

This metric shows the number of homes currently being lived in. It can help us gauge housing demand in an area.

-----------------------------------------------------------------------------------------

In [8]:
url = 'https://raw.githubusercontent.com/robertoaltran/Population/main/2018-SA1-dataset-individual-part-1-AucklandRegion_updated_28-7-20.csv'
data3 = pd.read_csv(url)

In [9]:
data3 = data3.iloc[:, [0, 1, 4] + list(range(61, 78)) + [80] + list(range(91, 94)) + list(range(346, 353))]

In [10]:
headers = data3.iloc[0]
data3 = data3[1:]
data3.columns = headers
data3.head()

,Area_Code,Area_Description,2018 Census,0-4 years,5-9 years,10-14 years,15-19 years,20-24 years,25-29 years,30-34 years,35-39 years,40-44 years,45-49 years,50-54 years,55-59 years,60-64 years,65-69 years,70-74 years,75-79 years,80-84 years,Median age(17),Under 15 years,15-29 years,30-64 years,Less than one year,1 year,2 years,3 years,4 years,5-9 years,10-19 years
1,110200,Okahukura Peninsula,1491,99,96,111,84,75,72,78,93,87,99,105,162,105,84,51,48,21,41.7,306,234,732,6,3,3,9,3,33,60
2,110300,Inlet Kaipara Harbour South,0,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C
3,110400,Cape Rodney,3525,216,234,237,168,153,168,177,201,204,240,264,312,291,258,198,123,51,45,687,489,1683,27,21,21,18,21,66,138
4,110500,Wellsford,1929,168,150,129,138,105,138,150,123,105,93,114,108,84,99,87,57,42,34.4,447,384,777,12,18,6,18,6,78,78
5,110600,Oceanic Auckland Region East,9,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,62,0,0,6,C,C,C,C,C,C,C


**Census usually resident population count**: 
  The total number of people who live in an area most of the time.

**Age in five year groups**: 
 Grouping people by age, like 0-5 years, 6-10 years, and so on.

**Age in broad groups**: 
 Grouping people by age in larger groups, like children, adults, and seniors.

**Years at usual residence**: 
 How many years a person has lived in their current home.

updated_28-7-20

-----------------------------------------------------------------------------------------

In [11]:
url = 'https://raw.githubusercontent.com/robertoaltran/Population/main/2018-SA1-dataset-individual-part-2-AucklandRegion.csv'
data4 = pd.read_csv(url)

In [12]:
data4 = data4.iloc[:, [0, 1] + list(range(174, 180)) + list(range(215, 226)) + list(range(264, 270))+ [274]]

In [13]:
headers = data4.iloc[0]
data4 = data4[1:]
data4.columns = headers

data4.head()

,Area_Code,Area_Description,No children,One child,Two children,Three children,Four children,Five children,No qualification,Level 1 certificate,Level 2 certificate,Level 3 certificate,Level 4 certificate,Level 5 diploma,Level 6 diploma,Bachelor degree and Level 7 qualification,Post-graduate and honours degrees,Masters degree,Doctorate degree,"$5,000 or less","$5,001 – $10,000","$10,001 – $20,000","$20,001 – $30,000","$30,001 – $50,000","$50,001 – $70,000",Median personal income($)
1,110200,Okahukura Peninsula,108,93,141,90,48,21,225,198,156,135,120,54,45,93,30,15,3,132,57,198,168,288,177,32600
2,110300,Inlet Kaipara Harbour South,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C
3,110400,Cape Rodney,315,156,378,246,120,33,495,357,321,249,315,129,150,333,102,81,39,312,123,504,408,642,393,32100
4,110500,Wellsford,150,87,159,144,75,33,381,219,186,141,132,57,48,90,30,15,0,192,72,321,270,303,195,25400
5,110600,Oceanic Auckland Region East,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,12600


### Feature Relevance for House Rental Price Model:

When predicting house rental prices in New Zealand, it's essential to determine the relevance of potential features. Below is a brief overview:


**Number of Children Born**: Can influence demand for property type and size.

**Education Metrics**: Locations near educational institutions or with a high student population might have specific rental demands.

**Income Metrics**: Areas with higher incomes might exhibit higher rental prices. The source of income can offer additional insights.

**Travel Means to Education**: Indicates transport infrastructure and proximity to educational establishments.

-----------------------------------------------------------------------------------------

In [14]:
url = 'https://raw.githubusercontent.com/robertoaltran/Population/main/2018-SA1-dataset-individual-part-3a-AucklandRegion.csv'
data5 = pd.read_csv(url)

In [15]:
data5 = data5.iloc[:, [0, 1] + list(range(16, 21)) + list(range(66, 73)) + list(range(156, 172))]

In [16]:
headers = data5.iloc[0]
data5 = data5[1:]
data5.columns = headers
data5.head()

,Area_Code,Area_Description,Employed Full time,Employed Part time,Unemployed,Not in the Labour Force,Total stated,Managers,Professionals,Technicians and Trades Workers,Community and Personal Service Workers,Clerical and Administrative Workers,Sales Workers,Machinery Operators and Drivers,Manufacturing,Electricity Gas Water and Waste Services,Construction,Wholesale Trade,Retail Trade,Accommodation and Food Services,Transport Postal and Warehousing,Information Media and Telecommunications,Financial and Insurance Services,Rental Hiring and Real Estate Services,Professional Scientific and Technical Services,Administrative and Support Services,Public Administration and Safety,Education and Training,Health Care and Social Assistance,Arts and Recreation Services
1,110200,Okahukura Peninsula,639,198,39,306,1182,204,93,117,75,66,66,81,72,3,114,42,57,39,42,6,12,15,42,39,24,48,54,9
2,110300,Inlet Kaipara Harbour South,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C
3,110400,Cape Rodney,1329,558,48,903,2838,507,309,246,147,186,147,93,165,6,264,90,126,111,60,27,21,51,156,72,24,141,135,57
4,110500,Wellsford,681,213,66,525,1485,156,96,144,78,87,117,81,90,3,153,45,114,78,54,3,15,6,63,33,15,54,54,12
5,110600,Oceanic Auckland Region East,C,C,C,6,9,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C


**Work and Labour Force Status**:
- This shows how many people in an area have jobs. Places with more people working might have higher rent prices because more people need homes.

**Status in Employment**:
- This tells us what kind of jobs people have, like full-time or part-time. Areas with many full-time workers might have higher rents because they have a steady income.

**Occupation by Residence & Workplace Address**:
- This information reveals the types of jobs people do and where they work. Areas with lots of high-paying jobs, like doctors or lawyers, might have higher rents. Also, if people live close to their work, they might be willing to pay more for rent.

**Industry by Residence & Workplace Address**:
- This tells us about the businesses and industries where people work. For instance, areas close to big business hubs might have higher rents. On the other hand, places with seasonal jobs might have different rent patterns.

-----------------------------------------------------------------------------------------

In [17]:
url = 'https://raw.githubusercontent.com/robertoaltran/Population/main/2018-SA1-dataset-individual-part-3b-AucklandRegion_updated_16-7-20.csv'
data6 = pd.read_csv(url, header = 1)

In [18]:
data6 = data6.iloc[:, [0, 1, 32 , 38, 41, 44, 50, 53, 56]]

In [19]:
data6.drop(0, inplace=True)
data6.reset_index(drop=True, inplace=True)
data6.rename(columns={'Unnamed: 0': 'Area_Code', 'Unnamed: 1': 'Area_Description'}, inplace=True)

In [20]:
data6.head()

,Area_Code,Area_Description,Work at home,"Drive a private car, truck or van","Drive a company car, truck or van","Passenger in a car, truck, van or company bus",Train,Bicycle,Walk or jog
0,110200,Okahukura Peninsula,168,315,78,12,0,0,18
1,110300,Inlet Kaipara Harbour South,C,C,C,C,C,C,C
2,110400,Cape Rodney,375,564,129,39,3,6,33
3,110500,Wellsford,57,315,108,39,0,3,81
4,110600,Oceanic Auckland Region East,C,C,C,C,C,C,C


**Main Means of Travel to Work by Residence & Workplace Address**:
- This shows how people get to their jobs, like by car, bus, or walking. Areas with good public transport might have higher rents because it's easier for people to get around. On the other hand, places where most people drive might need homes with parking spaces.

-----------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------

In [21]:
url = 'https://raw.githubusercontent.com/robertoaltran/Population/main/ANZSOC_Full%20Data_data-auckland.csv'  
data8 = pd.read_csv(url)
data8.head()

,ANZSOC Division,Year Month,Victimisations,Area Unit,Number of Records,Territorial Authority
0,"Abduction, Harassment and Other Related Offenc...",Dec-22,1,Mangere South.,1,Auckland.
1,"Abduction, Harassment and Other Related Offenc...",Oct-22,1,Royal Oak.,1,Auckland.
2,"Abduction, Harassment and Other Related Offenc...",Dec-22,1,Mascot.,1,Auckland.
3,"Abduction, Harassment and Other Related Offenc...",Dec-22,1,Balmoral.,1,Auckland.
4,"Abduction, Harassment and Other Related Offenc...",Oct-22,1,Drury.,1,Auckland.

In [22]:
data8['Area Unit'] = data8['Area Unit'].str.replace(r'\.$', '', regex=True)

## Auckland - Crime Categories and Incidents:

**Acts Intended to Cause Injury: 107,804 incidents**
This category involves deliberate acts where the intent was to inflict harm or injury to another individual.

**Sexual Assault and Related Offences: 10,113 incidents**
These are offenses that involve any unwanted sexual activity or behavior without the explicit consent of the victim.

**Abduction, Harassment and Other Related Offences Against Personal Liberty: 964 incidents**
This category encompasses crimes where a person's freedom or liberty is violated, including kidnapping and harassment.

**Robbery, Extortion and Related Offences: 13,617 incidents**
Such crimes involve forcibly taking something of value from another person, often coupled with threats or violence.

**Unlawful Entry With Intent/Burglary, Break and Enter: 257,424 incidents**
These are offenses where individuals unlawfully enter property, usually with the intent to commit theft or another crime.

**Theft and Related Offences: 658,869 incidents**
This category covers various forms of theft, from petty thefts to more significant robberies, excluding break-ins.

**The Grand Total of all reported crimes in Auckland during this period amounts to 1,048,791 incidents.**

### Source of Data:
The data is derived from the "Victimisation Time and Place" dataset, which offers detailed insights into when and where crimes occurred across Auckland.

In [23]:
data_crimes_2023 = data8[data8['Year Month'].str.contains('23')]
grouped_crimes = data_crimes_2023.groupby(['Area Unit', 'ANZSOC Division'])['Victimisations'].sum().reset_index()
pivot_crimes = grouped_crimes.pivot_table(index='Area Unit', columns='ANZSOC Division', values='Victimisations', fill_value=0).reset_index()

-----------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------

In [24]:
dataframes = [data2, data3, data4, data5, data6]
names = ['data2', 'data3', 'data4', 'data5', 'data6']

for df, name in zip(dataframes, names):
    if 'Area_Description' not in df.columns:
        print(f"{name} doesn't have 'Area_Description' column.")

In [25]:
merged_df = data2.merge(data3, on=['Area_Code', 'Area_Description'], how='outer')
merged_df = merged_df.merge(data4, on=['Area_Code', 'Area_Description'], how='outer')
merged_df = merged_df.merge(data5, on=['Area_Code', 'Area_Description'], how='outer')
merged_df = merged_df.merge(data6, on=['Area_Code', 'Area_Description'], how='outer')

In [26]:
merged_final = merged_df.merge(pivot_crimes, left_on='Area_Description', right_on='Area Unit', how='outer')

In [27]:
merged_final.head(20)

,Area_Code,Area_Description,2018.0,2018 Census,0-4 years,5-9 years,10-14 years,15-19 years,20-24 years,25-29 years,30-34 years,35-39 years,40-44 years,45-49 years,50-54 years,55-59 years,60-64 years,65-69 years,70-74 years,75-79 years,80-84 years,Median age(17),Under 15 years,15-29 years,30-64 years,Less than one year,1 year,2 years,3 years,4 years,5-9 years,10-19 years,No children,One child,Two children,Three children,Four children,Five children,No qualification,Level 1 certificate,Level 2 certificate,Level 3 certificate,Level 4 certificate,Level 5 diploma,Level 6 diploma,Bachelor degree and Level 7 qualification,Post-graduate and honours degrees,Masters degree,Doctorate degree,"$5,000 or less","$5,001 – $10,000","$10,001 – $20,000","$20,001 – $30,000","$30,001 – $50,000","$50,001 – $70,000",Median personal income($),Employed Full time,Employed Part time,Unemployed,Not in the Labour Force,Total stated,Managers,Professionals,Technicians and Trades Workers,Community and Personal Service Workers,Clerical and Administrative Workers,Sales Workers,Machinery Operators and Drivers,Manufacturing,Electricity Gas Water and Waste Services,Construction,Wholesale Trade,Retail Trade,Accommodation and Food Services,Transport Postal and Warehousing,Information Media and Telecommunications,Financial and Insurance Services,Rental Hiring and Real Estate Services,Professional Scientific and Technical Services,Administrative and Support Services,Public Administration and Safety,Education and Training,Health Care and Social Assistance,Arts and Recreation Services,Work at home,"Drive a private car, truck or van","Drive a company car, truck or van","Passenger in a car, truck, van or company bus",Train,Bicycle,Walk or jog,Area Unit,"Abduction, Harassment and Other Related Offences Against a Person",Acts Intended to Cause Injury,"Robbery, Extortion and Related Offences",Sexual Assault and Related Offences,Theft and Related Offences,"Unlawful Entry With Intent/Burglary, Break and Enter"
0,110200,Okahukura Peninsula,522.0,1491,99,96,111,84,75,72,78,93,87,99,105,162,105,84,51,48,21,41.7,306,234,732,6,3,3,9,3,33,60,108,93,141,90,48,21,225,198,156,135,120,54,45,93,30,15,3,132,57,198,168,288,177,32600,639,198,39,306,1182,204,93,117,75,66,66,81,72,3,114,42,57,39,42,6,12,15,42,39,24,48,54,9,168,315,78,12,0,0,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,110300,Inlet Kaipara Harbour South,0.0,0,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,110400,Cape Rodney,1275.0,3525,216,234,237,168,153,168,177,201,204,240,264,312,291,258,198,123,51,45,687,489,1683,27,21,21,18,21,66,138,315,156,378,246,120,33,495,357,321,249,315,129,150,333,102,81,39,312,123,504,408,642,393,32100,1329,558,48,903,2838,507,309,246,147,186,147,93,165,6,264,90,126,111,60,27,21,51,156,72,24,141,135,57,375,564,129,39,3,6,33,Cape Rodney,0.0,3.0,0.0,1.0,20.0,18.0
3,110500,Wellsford,654.0,1929,168,150,129,138,105,138,150,123,105,93,114,108,84,99,87,57,42,34.4,447,384,777,12,18,6,18,6,78,78,150,87,159,144,75,33,381,219,186,141,132,57,48,90,30,15,0,192,72,321,270,303,195,25400,681,213,66,525,1485,156,96,144,78,87,117,81,90,3,153,45,114,78,54,3,15,6,63,33,15,54,54,12,57,315,108,39,0,3,81,Wellsford,0.0,8.0,2.0,1.0,98.0,22.0
4,110600,Oceanic Auckland Region East,6.0,9,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,62,0,0,6,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,12600,C,C,C,6,9,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,110700,South Head,903.0,2595,171,174,207,159,96,126,165,132,159,213,234,213,165,174,114,66,21,42.2,546,384,1278,6,12,12,6,6,51,123,213,120,288,168,66,18,375,285,246,180,210,96,96,183,78,54,12,276,81,348,273,396,279,31900,1083,330,54,588,2049,357,252,237,114,147,90,72,120,3,201,66,93,21,54,15,24,39,111,51,57,114,108,45,228,405,132,33,0,0,9,South Head,0.0,3.0,0.0,0.0,10.0,14.0
6,110800,Kaipara Hills,630.0,1965,114,171,180,129,66,90,96,105,138,204,192,162,114,93,48,39,15,41.3,465,288,1008,6,9,3,6,18,78,153,174,108,192,117,42,15,252,186,171,162,168,81,57,141,75,33,9,219,60,219,195,282,228,34400,843,261,30,369,1500,264,204,174,78,117,87,66,75,15,165,69,72,42,39,12,27,21,135,33,45,81,69,24,123,303,99,30,0,0,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,110900,Dome Valley-Matakana,546.0,1530,84,99,120,87,51,45,48,78,99,126,126,135,111,126,99,51,21,46.6,306,189,726,6,9,9,6,15,45,93,135,69,198,108,36,15,180,129,117,105,105,45,75,198,78,48,12,153,51,186,150,231,165,34900,570,240,33,378,1224,207,183,111,72,69,69,27,66,3,99,36,81,72,21,12,15,30,114,33,21,51,51,15,132,246,72,21,0,0,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,111000,Oceanic Auckland Region West,0.0,0,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,111100,Warkworth West,960.0,2481,135,150,141,147,93,126,105,117,132,159,150,120,108,138,174,183,126,48.2,426,366,894,27,27,18,30,15,87,153,195,105,303,231,96,36,417,264,222,168,195,96,111,204,81,42,9,168,78,375,438,396,279,28900,834,291,33,897,2055,180,210,180,99,141,117,57,141,6,180,51,126,60,18,15,21,24,96,45,42,93,93,18,57,303,99,27,0,6,54,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,111200,Puhoi Valley,1242.0,3702,213,231,285,249,168,159,174,174,219,330,360,351,240,198,177,93,57,44.6,729,573,1848,24,18,18,39,21,96,297,375,171,411,231,102,27,369,345,318,267,306,141,150,396,216,117,36,348,144,426,387,525,405,36800,1554,564,66,792,2973,507,480,285,186,201,198,93,168,12,360,126,201,81,51,36,51,63,219,66,75,162,180,48,267,672,216,39,0,6,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,111300,Warkworth East,1125.0,3105,183,204,189,177,153,189,156,204,189,195,192,171,150,195,216,162,87,42.6,576,522,1257,42,39,36,42,39,150,261,315,135,381,234,90,21,426,330,249,240,240,132,138,273,126,69,12,240,108,510,399,531,327,30300,1146,411,48,924,2526,270,291,240,129,165,195,72,135,12,198,78,189,129,30,21,33,48,132,57,48,108,147,24,81,426,117,27,0,9,66,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,111400,Sandspit,393.0,969,24,45,51,45,33,36,27,30,42,75,78,87,87,102,93,60,30,54.7,123,114,426,3,18,3,12,0,30,63,99,48,132,84,27,3,96,102,90,69,81,51,54,135,57,36,6,81,24,138,105,183,114,37300,363,165,9,312,846,168,123,72,33,36,39,15,60,3,78,24,30,54,18,9,9,30,45,12,12,42,36,12,102,183,57,9,0,0,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,111500,Tawharanui Peninsula,783.0,1962,72,111,93,72,54,60,60,69,117,126,147,183,222,237,198,102,24,55,276,186,924,12,18,0,0,6,48,57,162,84,300,174,48,15,195,234,198,141,165,84,111,237,78,57,18,141,69,273,222,321,264,37700,693,318,21,651,1686,279,213,126,66,123,87,21,99,3,162,60,87,78,24,27,30,48,114,39,27,51,48,24,135,318,93,21,0,0,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,111600,Te Kuru,792.0,2484,165,213,186,180,99,135,147,171,171,252,201,180,132,99,66,54,18,38.8,561,414,1254,3,3,3,12,9,72,183,255,105,276,153,66,12,255,267,222,204,210,114,99,222,90,27,9,258,66,213,204,366,297,42400,1122,327,45,429,1920,342,315,195,114,162,141,72,126,9,231,102,150,42,33,18,57,36,117,72,57,111,111,36,153,444,156,30,0,3,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,111700,Snells Beach,1380.0,3405,186,213,207,162,126,147,186,177,183,201,189,222,219,291,300,192,123,47.9,606,438,1374,36,39,24,24,27,129,174,282,147,489,270,105,33,537,381,255,219,276,138,150,297,111,72,9,255,102,603,495,573,369,28500,1137,444,72,1149,2796,273,306,225,129,198,183,108,135,15,252,72,177,120,57,33,27,45,129,66,42,108,159,30,102,573,162,48,3,6,69,Snells Beach,0.0,2.0,2.0,1.0,23.0,10.0
16,111800,Barrier Islands,531.0,930,51,45,39,27,24,39,39,45,51,66,63,108,102,90,57,45,24,52.6,138,90,477,3,3,6,6,6,18,24,57,48,84,69,24,15,144,111,69,51,81,36,45,66,42,30,6,63,54,255,150,150,75,21300,279,168,57,285,792,111,69,45,57,42,33,24,12,0,66,0,33,57,33,12,3,9,33,18,24,42,33,27,84,117,33,6,0,6,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,111900,Algies Bay-Scotts Landing,498.0,1185,45,48,42,45,27,27,48,33,48,72,60,90,117,135,126,78,51,60.2,135,99,471,6,12,6,9,9,33,48,111,45,171,111,39,18,189,150,102,60,99,42,72,138,51,39,12,93,42,222,174,204,156,29500,327,168,24,528,1050,108,126,57,54,60,39,18,51,3,60,21,48,27,12,12,9,15,60,18,6,42,63,6,72,195,45,12,0,3,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,112000,Inlets other Auckland,9.0,12,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,58.5,0,0,6,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,13600,C,C,C,C,9,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,112100,Wainui-Waiwera,612.0,1674,63,99,129,105,99,69,69,90,96,138,135,168,123,105,78,57,24,45.6,291,276,819,12,9,18,3,6,54,138,186,72,195,102,51,15,162,171,153,150,126,69,78,186,57,39,12,156,66,201,162,270,204,37400,711,285,39,348,1383,222,216,120,96,132,81,45,69,9,165,60,87,30,33,15,15,24,117,42,39,69,105,24,117,306,108,15,0,0,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
# Obter valores únicos da coluna "Area_Description"
unique_values = merged_final['Area_Description'].unique()
# Filtrar apenas valores que são strings (excluindo NaN ou outros tipos)
string_values = [value for value in unique_values if isinstance(value, str)]

# Ordenar esses valores em ordem alfabética
sorted_unique_values = sorted(string_values)

# Imprimir os valores
for value in sorted_unique_values:
    print(value)

Akoranga
Albany Central
Albany Heights
Albany South
Albany West
Alfriston
Algies Bay-Scotts Landing
Anselmi Ridge
Anzac Avenue
Aorere Central
Aorere North
Aorere South
Ararimu
Ardmore
Army Bay
Auckland Airport
Auckland-University
Avondale Central (Auckland)
Avondale North (Auckland)
Avondale Rosebank
Avondale South (Auckland)
Avondale West (Auckland)
Awaruku
Awhitu
Balmoral
Barrier Islands
Baverstock
Bays Waiheke Island
Bayswater
Bayview East
Bayview South
Bayview West
Beach Haven East
Beach Haven South
Beach Haven West
Belmont (Auckland)
Birdwood West
Birkdale North
Birkdale South
Birkenhead North
Birkenhead South
Birkenhead West
Blockhouse Bay East
Blockhouse Bay North
Blockhouse Bay North East
Blockhouse Bay South
Bombay Hills
Botany Central
Botany Downs East
Botany Downs West
Botany East
Botany Junction
Botany North
Botany South
Browns Bay Central
Browns Bay South East
Browns Bay South West
Buckland
Bucklands Beach Central
Bucklands Beach North
Bucklands Beach South
Burbank
Burswood
Campbells Bay
Cape Hill
Cape Rodney
Castor Bay
Chapel Downs
Chatswood
Cheltenham
Clarks Beach
Clendon Park East
Clendon Park North
Clendon Park West
Clevedon
Clover Park North
Clover Park South
Cloverlea (Auckland)
Coatesville
Cockle Bay
Conifer Grove East
Conifer Grove West
Dairy Flat North
Dairy Flat South
Dairy Flat West
Dannemora North
Dannemora South
Devonport
Dingwall
Dome Valley-Matakana
Donegal Park
Drury
Drury Rural
East Tamaki
East Tamaki Heights
Eastern Beach
Eden Park
Eden Terrace
Eden Valley
Ellerslie Central
Ellerslie East
Ellerslie South
Ellerslie West
Epsom Central-North
Epsom Central-South
Epsom East
Epsom North
Epsom South
Fairview Heights
Farm Cove
Favona East
Favona North
Favona West
Ferguson
Forrest Hill East
Forrest Hill North
Forrest Hill West
Freemans Bay
Fruitvale
Glamorgan
Glen Eden Central
Glen Eden North
Glen Eden Rosier
Glen Eden West
Glen Eden Woodglen
Glen Innes East-Wai O Taiki Bay
Glen Innes West
Glenavon
Glenbrook
Glendene North
Glendene South
Glendowie North
Glendowie South
Glenfield Central
Glenfield East
Glenfield North
Glenfield South West
Glenfield West
Golflands
Goodwood Heights
Grafton
Grange
Green Bay North
Green Bay South
Greenhithe East
Greenhithe South
Greenhithe West
Greenlane North
Greenlane South
Grey Lynn Central
Grey Lynn East
Grey Lynn North
Grey Lynn West
Gulf Harbour North
Gulf Harbour South
Gulf Islands
Half Moon Bay North East
Half Moon Bay South East
Half Moon Bay West
Hamilton Estate
Harania North
Harania South
Hatfields Beach
Hauraki
Helensville
Helensville Rural
Henderson Central
Henderson East
Henderson Larnoch
Henderson Lincoln East
Henderson Lincoln South
Henderson Lincoln West
Henderson North
Henderson North East
Henderson Valley
Henderson Valley Park
Herne Bay
Highland Park (Auckland)
Hillcrest East (Auckland)
Hillcrest North (Auckland)
Hillcrest West (Auckland)
Hillpark North
Hillpark South
Hillsborough East (Auckland)
Hillsborough North (Auckland)
Hillsborough South (Auckland)
Hillsborough West (Auckland)
Hilltop (Auckland)
Hingaia
Hobson Ridge Central
Hobson Ridge North
Hobson Ridge South
Hobsonville
Hobsonville Point
Homai East
Homai West
Howick Central
Howick East
Howick West
Huntington Park
Hunua
Inlet Kaipara Harbour South
Inlet Manukau Harbour
Inlet Waitemata Harbour
Inlets other Auckland
Kaipara Hills
Karaka Creek
Karaka Lakes
Karangahape
Kaurilands
Kawakawa Bay-Orere
Kelston North
Kelston South
Kendallvale
Kingseat-Karaka
Kingsland
Kingsway
Kohimarama
Konini
Kumeu Rural East
Kumeu Rural West
Kumeu-Huapai
Laingholm
Leabank
Long Bay
Lynfield North
Lynfield South
Mairangi Bay North
Mairangi Bay South
Mangere Bridge
Mangere Bridge Ambury
Mangere Central
Mangere East
Mangere Mascot
Mangere Mountain View
Mangere North
Mangere South
Mangere South East
Mangere West
Manly East
Manly West
Manukau Central
Manurewa Central
Manurewa East
Manurewa South
Maraetai
Massey Central
Massey East
Massey Road North
Massey Road South
Massey Road West
Massey Royal Road West
Massey South
Massey West
Maungawhau
McLaren Park
Meadowbank East
Meadowbank West
Mellons Bay
Middlemore
Milford Central
Milford West
Millwater North
Millwater South
Mission Bay
Mission Heights North
Mission Heights South
Morningside (Auckland)
Mount Albert Central
Mount Albert North
Mount Albert South
Mount Albert West
Mount Eden East
Mount Eden North
Mount Eden North East
Mount Eden South
Mount Eden West
Mount Roskill Central North
Mount Roskill Central South
Mount Roskill North
Mount Roskill South
Mount Roskill White Swan
Mount St John
Mount Wellington Central
Mount Wellington East
Mount Wellington Ferndale
Mount Wellington Industrial
Mount Wellington North East
Mount Wellington North West
Mount Wellington South East
Mount Wellington South West
Mount Wellington West
Muriwai
Muriwai Valley-Bethells Beach
Murrays Bay East
Murrays Bay West
Narrow Neck
New Lynn Central
New Lynn Central South
New Lynn North
New Lynn North West
New Lynn Seabrook
New Lynn South
New Windsor North
New Windsor South
Newmarket
North Harbour
Northcote Central (Auckland)
Northcote Point (Auckland)
Northcote South (Auckland)
Northcote Tuff Crater
Northcross
Northpark North
Northpark South
Oceanic Auckland Region East
Oceanic Auckland Region West
Okahukura Peninsula
Okura Bush
One Tree Hill
Onehunga Central
Onehunga North
Onehunga West
Onehunga-Te Papapa Industrial
Oneroa East-Palm Beach
Oneroa West
Onetangi
Opaheke
Orakei East
Orakei West
Oranga
Oratia
Orewa Central
Orewa North
Orewa South
Ormiston East
Ormiston North
Ormiston South
Ostend
Otahuhu Central
Otahuhu East
Otahuhu Industrial
Otahuhu North
Otahuhu South
Otahuhu South West
Otara Central
Otara East
Otara South
Otara West
Oteha East
Oteha West
Owairaka East
Owairaka West
Pahurehure
Pakuranga Central
Pakuranga Heights East
Pakuranga Heights North West
Pakuranga Heights South West
Pakuranga West
Panmure East
Panmure Glen Innes Industrial
Panmure West
Papakura Central
Papakura East
Papakura Industrial
Papakura Kelvin
Papakura Massey Park
Papakura North
Papakura North East
Papakura West
Papatoetoe Central
Papatoetoe East
Papatoetoe North
Papatoetoe South
Papatoetoe South West
Papatoetoe West
Parakai
Paremoremo East
Paremoremo West
Parnell East
Parnell West
Patumahoe
Penrose
Piha
Pinehill
Point Chevalier East
Point Chevalier West
Point England
Ponsonby East
Ponsonby West
Puhinui East
Puhinui North
Puhinui South
Puhoi Valley
Pukekohe Central
Pukekohe Hospital
Pukekohe North West
Pukekohe West
Puni
Quay Street-Customs Street
Queen Street
Queen Street South West
Ramarama
Randwick Park East
Randwick Park West
Ranui Domain
Ranui North
Ranui South East
Ranui South West
Red Beach East
Red Beach West
Red Hill
Redcastle
Remuera Abbotts Park
Remuera East
Remuera North
Remuera South
Remuera Waiata
Remuera Waiatarua
Remuera Waitaramoa
Remuera West
Riverhead
Riverhead Forest
Rongomai East
Rongomai West
Rooseville Park
Rosa Birch Park
Rosebank Peninsula
Rosehill
Rothesay Bay
Rowandale East
Rowandale West
Royal Heights North
Royal Heights South
Royal Oak East (Auckland)
Royal Oak West (Auckland)
Saint Heliers North
Saint Heliers South
Saint Heliers West
Saint Johns East
Saint Johns West
Saint Marys Bay
Sandringham Central
Sandringham East
Sandringham North
Sandringham West
Sandspit
Schnapper Rock
Shelly Park
Shortland Street
Silverdale Central (Auckland)
Silverdale South (Auckland)
Snells Beach
Somerville
South Head
St Lukes
Stanley Point
Stanmore Bay East
Stanmore Bay West
Stonefields East
Stonefields West
Summerland North
Summerland South
Sunkist Bay
Sunnyhills East
Sunnyhills West-Pakuranga North
Sunnynook North
Sunnynook South
Sunnyvale East
Sunnyvale West-Parrs Park
Surfdale
Sutton Park
Swanson
Swanson Rural
Sylvia Park
Symonds Street East
Symonds Street North West
Symonds Street West
Takanini Central
Takanini Industrial
Takanini North
Takanini South
Takanini South East
Takanini West
Takapuna Central
Takapuna South
Takapuna West
Tamakae
Tamaki
Taupaki
Tawharanui Peninsula
Te Atatu Peninsula Central
Te Atatu Peninsula East
Te Atatu Peninsula North West
Te Atatu Peninsula West
Te Atatu South-Central
Te Atatu South-Edmonton
Te Atatu South-McLeod North
Te Atatu South-McLeod South
Te Kuru
Te Papapa
Te Puru
The Gardens (Auckland)
The Strand
Three Kings East
Three Kings West
Tindalls-Matakatia
Titirangi South
Torbay
Totara Heights
Totara Vale North
Totara Vale South
Turanga
Tuscany Heights
Unsworth Heights East
Unsworth Heights West
Victoria Park
Vipond
Waiake
Waiatarua
Waiheke East
Waikoukou Valley
Waikowhai North
Waikowhai South
Waima-Woodlands Park
Waimauku
Wainui-Waiwera
Waipatukahu
Wairau Valley
Waitakere
Waitakere Ranges North
Waitakere Ranges South
Waitoki
Waiuku Central
Waiuku East
Warkworth East
Warkworth West
Waterview
Wattle Downs East
Wattle Downs North
Wattle Downs West
Wellsford
Wesley East
Wesley South
Wesley West
West Harbour Clearwater Cove
West Harbour Luckens Point
West Harbour West
West Lynn
Western Heights (Auckland)
Westgate Central
Westgate South
Westlake
Westmere North
Westmere South-Western Springs
Weymouth East
Weymouth North
Weymouth South
Whangaparoa Central
Whenuapai
Windsor Park
Wiri East
Wiri West
Wynyard-Viaduct

In [32]:

# Removendo a designação de direção e a parte '(Auckland)' para padronizar os nomes dos bairros
merged_final['Area_Description'] = merged_final['Area_Description'].str.replace(r' (North|South|East|West|Central)\b', '', regex=True)
merged_final['Area_Description'] = merged_final['Area_Description'].str.replace(r' \(Auckland\)', '', regex=True)

# Agora, vamos agrupar por 'Area_Description' e somar os valores
merged_final_grouped = merged_final.groupby('Area_Description').sum().reset_index()

              Area_Description  2018.0  \
0                     Akoranga   405.0
1                       Albany  2187.0
2               Albany Heights  1053.0
3                    Alfriston  1059.0
4    Algies Bay-Scotts Landing   498.0
..                         ...     ...
349                Whangaparoa  1350.0
350                  Whenuapai  1263.0
351               Windsor Park   642.0
352                       Wiri   999.0
353            Wynyard-Viaduct   630.0

     Abduction, Harassment and Other Related Offences Against a Person  \
0                                                  0.0
1                                                  0.0
2                                                  0.0
3                                                  0.0
4                                                  0.0
..                                                 ...
349                                                0.0
350                                                0.0
351                                                0.0
352                                                0.0
353                                                0.0

     Acts Intended to Cause Injury  Robbery, Extortion and Related Offences  \
0                              0.0                                      0.0
1                              0.0                                      0.0
2                              0.0                                      0.0
3                              0.0                                      0.0
4                              0.0                                      0.0
..                             ...                                      ...
349                            0.0                                      0.0
350                            0.0                                      0.0
351                           15.0                                      3.0
352                            0.0                                      0.0
353                            0.0                                      0.0

     Sexual Assault and Related Offences  Theft and Related Offences  \
0                                    0.0                         0.0
1                                    0.0                         0.0
2                                    0.0                         0.0
3                                    0.0                         0.0
4                                    0.0                         0.0
..                                   ...                         ...
349                                  0.0                         0.0
350                                  0.0                         0.0
351                                  3.0                       232.0
352                                  0.0                         0.0
353                                  0.0                         0.0

     Unlawful Entry With Intent/Burglary, Break and Enter
0                                                  0.0
1                                                  0.0
2                                                  0.0
3                                                  0.0
4                                                  0.0
..                                                 ...
349                                                0.0
350                                                0.0
351                                               27.0
352                                                0.0
353                                                0.0

[354 rows x 8 columns]

In [33]:
# Obter valores únicos da coluna "Area_Description"
unique_values = merged_final_grouped['Area_Description'].unique()
# Filtrar apenas valores que são strings (excluindo NaN ou outros tipos)
string_values = [value for value in unique_values if isinstance(value, str)]

# Ordenar esses valores em ordem alfabética
sorted_unique_values = sorted(string_values)

# Imprimir os valores
for value in sorted_unique_values:
    print(value)

Akoranga
Albany
Albany Heights
Alfriston
Algies Bay-Scotts Landing
Anselmi Ridge
Anzac Avenue
Aorere
Ararimu
Ardmore
Army Bay
Auckland Airport
Auckland-University
Avondale
Avondale Rosebank
Awaruku
Awhitu
Balmoral
Barrier Islands
Baverstock
Bays Waiheke Island
Bayswater
Bayview
Beach Haven
Belmont
Birdwood
Birkdale
Birkenhead
Blockhouse Bay
Bombay Hills
Botany
Botany Downs
Botany Junction
Browns Bay
Buckland
Bucklands Beach
Burbank
Burswood
Campbells Bay
Cape Hill
Cape Rodney
Castor Bay
Chapel Downs
Chatswood
Cheltenham
Clarks Beach
Clendon Park
Clevedon
Clover Park
Cloverlea
Coatesville
Cockle Bay
Conifer Grove
Dairy Flat
Dannemora
Devonport
Dingwall
Dome Valley-Matakana
Donegal Park
Drury
Drury Rural
East Tamaki
East Tamaki Heights
Eastern Beach
Eden Park
Eden Terrace
Eden Valley
Ellerslie
Epsom
Epsom-North
Epsom-South
Fairview Heights
Farm Cove
Favona
Ferguson
Forrest Hill
Freemans Bay
Fruitvale
Glamorgan
Glen Eden
Glen Eden Rosier
Glen Eden Woodglen
Glen Innes
Glen Innes-Wai O Taiki Bay
Glenavon
Glenbrook
Glendene
Glendowie
Glenfield
Golflands
Goodwood Heights
Grafton
Grange
Green Bay
Greenhithe
Greenlane
Grey Lynn
Gulf Harbour
Gulf Islands
Half Moon Bay
Hamilton Estate
Harania
Hatfields Beach
Hauraki
Helensville
Helensville Rural
Henderson
Henderson Larnoch
Henderson Lincoln
Henderson Valley
Henderson Valley Park
Herne Bay
Highland Park
Hillcrest
Hillpark
Hillsborough
Hilltop
Hingaia
Hobson Ridge
Hobsonville
Hobsonville Point
Homai
Howick
Huntington Park
Hunua
Inlet Kaipara Harbour
Inlet Manukau Harbour
Inlet Waitemata Harbour
Inlets other Auckland
Kaipara Hills
Karaka Creek
Karaka Lakes
Karangahape
Kaurilands
Kawakawa Bay-Orere
Kelston
Kendallvale
Kingseat-Karaka
Kingsland
Kingsway
Kohimarama
Konini
Kumeu Rural
Kumeu-Huapai
Laingholm
Leabank
Long Bay
Lynfield
Mairangi Bay
Mangere
Mangere Bridge
Mangere Bridge Ambury
Mangere Mascot
Mangere Mountain View
Manly
Manukau
Manurewa
Maraetai
Massey
Massey Road
Massey Royal Road
Maungawhau
McLaren Park
Meadowbank
Mellons Bay
Middlemore
Milford
Millwater
Mission Bay
Mission Heights
Morningside
Mount Albert
Mount Eden
Mount Roskill
Mount Roskill White Swan
Mount St John
Mount Wellington
Mount Wellington Ferndale
Mount Wellington Industrial
Muriwai
Muriwai Valley-Bethells Beach
Murrays Bay
Narrow Neck
New Lynn
New Lynn Seabrook
New Windsor
Newmarket
North Harbour
Northcote
Northcote Point
Northcote Tuff Crater
Northcross
Northpark
Oceanic Auckland Region
Okahukura Peninsula
Okura Bush
One Tree Hill
Onehunga
Onehunga-Te Papapa Industrial
Oneroa
Oneroa-Palm Beach
Onetangi
Opaheke
Orakei
Oranga
Oratia
Orewa
Ormiston
Ostend
Otahuhu
Otahuhu Industrial
Otara
Oteha
Owairaka
Pahurehure
Pakuranga
Pakuranga Heights
Panmure
Panmure Glen Innes Industrial
Papakura
Papakura Industrial
Papakura Kelvin
Papakura Massey Park
Papatoetoe
Parakai
Paremoremo
Parnell
Patumahoe
Penrose
Piha
Pinehill
Point Chevalier
Point England
Ponsonby
Puhinui
Puhoi Valley
Pukekohe
Pukekohe Hospital
Puni
Quay Street-Customs Street
Queen Street
Ramarama
Randwick Park
Ranui
Ranui Domain
Red Beach
Red Hill
Redcastle
Remuera
Remuera Abbotts Park
Remuera Waiata
Remuera Waiatarua
Remuera Waitaramoa
Riverhead
Riverhead Forest
Rongomai
Rooseville Park
Rosa Birch Park
Rosebank Peninsula
Rosehill
Rothesay Bay
Rowandale
Royal Heights
Royal Oak
Saint Heliers
Saint Johns
Saint Marys Bay
Sandringham
Sandspit
Schnapper Rock
Shelly Park
Shortland Street
Silverdale
Snells Beach
Somerville
South Head
St Lukes
Stanley Point
Stanmore Bay
Stonefields
Summerland
Sunkist Bay
Sunnyhills
Sunnyhills-Pakuranga
Sunnynook
Sunnyvale
Sunnyvale-Parrs Park
Surfdale
Sutton Park
Swanson
Swanson Rural
Sylvia Park
Symonds Street
Takanini
Takanini Industrial
Takapuna
Tamakae
Tamaki
Taupaki
Tawharanui Peninsula
Te Atatu Peninsula
Te Atatu-Central
Te Atatu-Edmonton
Te Atatu-McLeod
Te Kuru
Te Papapa
Te Puru
The Gardens
The Strand
Three Kings
Tindalls-Matakatia
Titirangi
Torbay
Totara Heights
Totara Vale
Turanga
Tuscany Heights
Unsworth Heights
Victoria Park
Vipond
Waiake
Waiatarua
Waiheke
Waikoukou Valley
Waikowhai
Waima-Woodlands Park
Waimauku
Wainui-Waiwera
Waipatukahu
Wairau Valley
Waitakere
Waitakere Ranges
Waitoki
Waiuku
Warkworth
Waterview
Wattle Downs
Wellsford
Wesley
West Harbour
West Harbour Clearwater Cove
West Harbour Luckens Point
West Lynn
Western Heights
Westgate
Westlake
Westmere
Westmere-Western Springs
Weymouth
Whangaparoa
Whenuapai
Windsor Park
Wiri
Wynyard-Viaduct